name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Submodules
      run: git submodule update
    - name: cythonize
      run: |
        pip install cython
        python3 setup.py build_ext --inplace
    - uses: actions/upload-artifact@master
      with:
        name: code
        path: .

